force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/ParentProcessId__c.field-meta.xml
<CustomField>
    <fullName>ParentProcessId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentProcessId</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Child Processes</relationshipLabel>
    <relationshipName>ChildProcesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/ProcessTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ProcessTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProcessTemplateId</label>
    <referenceTo>Process_Template__c</referenceTo>
    <relationshipLabel>Processes</relationshipLabel>
    <relationshipName>Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/fields/StepNumber__c.field-meta.xml
<CustomField>
    <fullName>StepNumber__c</fullName>
    <label>StepNumber</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/Steps_To_Complete__c.field-meta.xml
<CustomField>
    <fullName>Steps_To_Complete__c</fullName>
    <label>Steps To Complete</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <label>TargetObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Template__c/Process_Template__c.object-meta.xml
<CustomObject>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CompletedProcessesCtrl.cls
public with sharing class CompletedProcessesCtrl {
    @AuraEnabled(cacheable=true)
    public static List<Process__c> getCompletedProcesses(Id targetObjectId) {
        return [
            SELECT Id, Name, Status__c, StepNumber__c, CreatedDate, ProcessTemplateId__r.Name, Completed_Date__c, Owner.Name, TargetObjectId__c,
                (SELECT Id, Name, Status__c, StepNumber__c, Steps_To_Complete__c, Due_Date__c, Owner.Name, Completed_Date__c
                 FROM ChildProcesses__r
                 ORDER BY StepNumber__c ASC)
            FROM Process__c
            WHERE TargetObjectId__c = :targetObjectId
              AND ParentProcessId__c = null
              AND Status__c = 'Completed'
            ORDER BY CreatedDate DESC
        ];
    }
}